<?php

namespace ContainerYR8xhfd;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_JzJ5M2nService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.JzJ5M2n' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.JzJ5M2n'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\MessageController::index' => ['privates', '.service_locator.HIQHt62', 'get_ServiceLocator_HIQHt62Service', true],
            'App\\Controller\\MessageController::show' => ['privates', '.service_locator.tQUwO87', 'get_ServiceLocator_TQUwO87Service', true],
            'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.zFcJjKU', 'get_ServiceLocator_ZFcJjKUService', true],
            'App\\Controller\\SujetController::show' => ['privates', '.service_locator.HIQHt62', 'get_ServiceLocator_HIQHt62Service', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Kernel::terminate' => ['privates', '.service_locator.bRdave9', 'get_ServiceLocator_BRdave9Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::terminate' => ['privates', '.service_locator.bRdave9', 'get_ServiceLocator_BRdave9Service', true],
            'App\\Controller\\MessageController:index' => ['privates', '.service_locator.HIQHt62', 'get_ServiceLocator_HIQHt62Service', true],
            'App\\Controller\\MessageController:show' => ['privates', '.service_locator.tQUwO87', 'get_ServiceLocator_TQUwO87Service', true],
            'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.zFcJjKU', 'get_ServiceLocator_ZFcJjKUService', true],
            'App\\Controller\\SujetController:show' => ['privates', '.service_locator.HIQHt62', 'get_ServiceLocator_HIQHt62Service', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel:terminate' => ['privates', '.service_locator.bRdave9', 'get_ServiceLocator_BRdave9Service', true],
        ], [
            'App\\Controller\\MessageController::index' => '?',
            'App\\Controller\\MessageController::show' => '?',
            'App\\Controller\\SecurityController::login' => '?',
            'App\\Controller\\SujetController::show' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::terminate' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'kernel::terminate' => '?',
            'App\\Controller\\MessageController:index' => '?',
            'App\\Controller\\MessageController:show' => '?',
            'App\\Controller\\SecurityController:login' => '?',
            'App\\Controller\\SujetController:show' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:terminate' => '?',
        ]);
    }
}
