<?php

namespace ContainerYKjYl1J;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_AQuXzxFService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.AQuXzxF' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.AQuXzxF'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'messageRepository' => ['privates', 'App\\Repository\\MessageRepository', 'getMessageRepositoryService', true],
            'sujet' => ['privates', '.errored..service_locator.AQuXzxF.App\\Entity\\Sujet', NULL, 'Cannot autowire service ".service_locator.AQuXzxF": it references class "App\\Entity\\Sujet" but no such service exists.'],
        ], [
            'messageRepository' => 'App\\Repository\\MessageRepository',
            'sujet' => 'App\\Entity\\Sujet',
        ]);
    }
}
