<?php

namespace ContainerYKjYl1J;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSujetService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.AQuXzxF.App\Entity\Sujet' shared service.
     *
     * @return \App\Entity\Sujet
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.AQuXzxF": it references class "App\\Entity\\Sujet" but no such service exists.');
    }
}
