<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZgPJBiX\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZgPJBiX/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerZgPJBiX.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerZgPJBiX\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerZgPJBiX\App_KernelDevDebugContainer([
    'container.build_hash' => 'ZgPJBiX',
    'container.build_id' => '28ad71c8',
    'container.build_time' => 1652436141,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZgPJBiX');
