<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYR8xhfd\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYR8xhfd/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerYR8xhfd.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerYR8xhfd\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerYR8xhfd\App_KernelDevDebugContainer([
    'container.build_hash' => 'YR8xhfd',
    'container.build_id' => '08472952',
    'container.build_time' => 1652456396,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerYR8xhfd');
