<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGGKeaq5\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGGKeaq5/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerGGKeaq5.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerGGKeaq5\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerGGKeaq5\App_KernelDevDebugContainer([
    'container.build_hash' => 'GGKeaq5',
    'container.build_id' => '6ea359fd',
    'container.build_time' => 1652384575,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerGGKeaq5');
